In [ ]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [ ]:
# Importing necessary libraries
import numpy as np                # For working with numbers and arrays
import pandas as pd              # For handling and analyzing data

# Importing machine learning tools from scikit-learn
from sklearn.model_selection import train_test_split  # To split data into training and testing
from sklearn.linear_model import LogisticRegression   # To build a logistic regression model
from sklearn.metrics import accuracy_score            # To measure how accurate the model is

In [ ]:
# Import the files module from google.colab
# This module allows you to upload files from your local machine to the Colab environment
from google.colab import files
# Upload files from your local machine
# The uploaded files will be stored in the 'uploaded' variable as a dictionary
uploaded = files.upload()

Saving heart_disease_data.csv to heart_disease_data.csv

In [ ]:
import pandas as pd
# The read_csv function loads the data from the CSV file into a DataFrame
heart_data = pd.read_csv('heart_disease_data.csv')

# Display the DataFrame
heart_data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [ ]:
heart_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [ ]:
heart_data.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [ ]:
heart_data.shape

(303, 14)

In [ ]:
heart_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [ ]:
# checking for missing values
heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
# statistical measures about the data
heart_data.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

### **splitting ffeatures and targets**

In [ ]:
X = heart_data.drop(columns='target', axis=1) #telling to pandas to use variable x to represent all values of the table, except for column target . . . .axis=1 means use the column. because we use 1 for column and 0 for rows.
Y = heart_data['target']

In [ ]:
print(X)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal
0        0   0     1
1        0   0     2
2        2   0     2
3        2   0     2
4        2   0     2
..     ...  ..   ...
298      1   0     3
299      1   0     3
300      1   2     3
301      1   1     3
302      1   1     2

[303 rows x 13 columns]

In [ ]:
print(Y)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

# **Splitting the Data into training data and test data**

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2) #random_state=2 mean make fixed spliting , not random.

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(303, 13) (242, 13) (61, 13)

# ***MODEL TRAINING***

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

# Initialize the KNN model
model = KNeighborsClassifier()

In [ ]:
#trainig the KNN model with training data
model.fit(X_train, Y_train)

KNeighborsClassifier()

In [ ]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.78099173553719

In [ ]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print('Accuracy on Test data : ', test_data_accuracy)

Accuracy on Test data :  0.6229508196721312

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier


model = KNeighborsClassifier()

# Define the parameter grid
param_grid = {
    'n_neighbors': [3, 5, 7, 9, 11], # initially the computer used 5 neighbours in default, so now we are telling for the model to trian first with 3, then with 5, then with 7, 9 and finally with 11 .. . .check all one by one
    'weights': ['uniform', 'distance'],    #giving  the same or equal weight first, and then distant (meaning neighbours have higher weight than the distant).
    'metric': ['euclidean', 'manhattan', 'minkowski'] # yetignawn qemer lkebel . . . .yemilewn check yadegal.
}

# Initialize GridSearchCV
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, scoring='accuracy', n_jobs=-1)

# Fit the grid search to the data
grid_search.fit(X_train, Y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'metric': ['euclidean', 'manhattan', 'minkowski'],
                         'n_neighbors': [3, 5, 7, 9, 11],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [ ]:
# Get the best parameters and the best score
best_params = grid_search.best_params_
best_score = grid_search.best_score_

In [ ]:
best_model = grid_search.best_estimator_

# Make predictions on the test set
y_pred = best_model.predict(X_test)

In [ ]:
# accuracy on test data
test_data_accuracy = accuracy_score(y_pred, Y_test)
print('Accuracy on Test data : ', test_data_accuracy)

Accuracy on Test data :  0.6557377049180327

In [ ]:


# Train the model
model.fit(X_train, Y_train)

KNeighborsClassifier()

In [ ]:
input_data = (62,0,0,140,268,0,0,160,0,3.6,0,2,2)

# change the input data to a numpy array
input_data_as_numpy_array= np.asarray(input_data)

# reshape the numpy array as we are predicting for only on instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)
print(prediction)

if (prediction[0]== 0):
  print('The Person does not have a Heart Disease')
else:
  print('The Person has Heart Disease')

[1]
The Person has Heart Disease

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

# ***RANDOM FOREST***

In [ ]:
# Import the Random Forest classification algorithm from scikit-learn
from sklearn.ensemble import RandomForestClassifier

# Import accuracy_score to calculate the percentage of correct predictions
from sklearn.metrics import accuracy_score

# Import precision_score to measure how many predicted positive cases were actually positive
from sklearn.metrics import precision_score

# Import recall_score to measure how many actual positive cases were correctly detected
from sklearn.metrics import recall_score

# Import f1_score to calculate the balance between precision and recall
from sklearn.metrics import f1_score

# Import confusion_matrix to see the number of TP, TN, FP, and FN predictions
from sklearn.metrics import confusion_matrix

In [ ]:
# Create a Random Forest classifier with 200 decision trees
rf_model = RandomForestClassifier(

    # Use 200 trees to make the model more stable than using only a few trees
    n_estimators=200,

    # Set a fixed random seed so we get reproducible results every time
    random_state=2
)

In [ ]:
# Train the Random Forest model using the training features and training labels
rf_model.fit(X_train, Y_train)

RandomForestClassifier(n_estimators=200, random_state=2)

In [ ]:
# Use the trained Random Forest model to predict the training data
Y_train_prediction = rf_model.predict(X_train)

In [ ]:
# Calculate the percentage of training predictions that are correct
training_accuracy = accuracy_score(Y_train, Y_train_prediction)

# Print the training accuracy
print("Training Accuracy:", training_accuracy)

Training Accuracy: 1.0

In [ ]:
# Use the trained Random Forest model to predict the unseen test data
Y_test_prediction = rf_model.predict(X_test)

In [ ]:
# Calculate the percentage of test predictions that are correct
test_accuracy = accuracy_score(Y_test, Y_test_prediction)

# Print the test accuracy
print("Test Accuracy:", test_accuracy)

Test Accuracy: 0.7540983606557377

In [ ]:
# Calculate precision using the actual test labels and predicted test labels
test_precision = precision_score(Y_test, Y_test_prediction)

# Print the test precision
print("Test Precision:", test_precision)

Test Precision: 0.78125

In [ ]:
# Calculate recall to see how many actual heart-disease cases were detected
test_recall = recall_score(Y_test, Y_test_prediction)


print("Test Recall:", test_recall)

Test Recall: 0.7575757575757576

In [ ]:
# Calculate the F1 score, which balances precision and recall
test_f1 = f1_score(Y_test, Y_test_prediction)

print("Test F1 Score:", test_f1)

Test F1 Score: 0.7692307692307693

In [ ]:
# Print a heading to make the results easier to read
print("Random Forest Results")


print("Training Accuracy :", training_accuracy)

print("Test Accuracy     :", test_accuracy)

print("Test Precision    :", test_precision)

print("Test Recall       :", test_recall)

print("Test F1 Score     :", test_f1)

Random Forest Results
Training Accuracy : 1.0
Test Accuracy     : 0.7540983606557377
Test Precision    : 0.78125
Test Recall       : 0.7575757575757576
Test F1 Score     : 0.7692307692307693

In [ ]:
# Calculate the confusion matrix using the actual and predicted test labels
cm = confusion_matrix(Y_test, Y_test_prediction)

print("Confusion Matrix:")

# Display the confusion matrix
print(cm)

Confusion Matrix:
[[21  7]
 [ 8 25]]

In [ ]:
# Import cross_val_score so we can evaluate the model using multiple train/validation splits
from sklearn.model_selection import cross_val_score

# Perform 5-fold cross-validation using the training dataset
cv_scores = cross_val_score(

    # Use our Random Forest model
    rf_model,

    # Use the training features
    X_train,

    # Use the training target values
    Y_train,

    # Divide the training data into 5 folds
    cv=5,

    # Use accuracy as the evaluation metric
    scoring='accuracy'
)

# Print the accuracy obtained from each fold
print("Cross-validation scores:", cv_scores)

# Calculate and print the average cross-validation accuracy
print("Mean CV Accuracy:", cv_scores.mean())

Cross-validation scores: [0.85714286 0.91836735 0.79166667 0.9375     0.75      ]
Mean CV Accuracy: 0.8509353741496598

In [ ]:
# Import GridSearchCV for testing different Random Forest parameter combinations
from sklearn.model_selection import GridSearchCV

# Create a smaller parameter grid to make the search much faster
param_grid = {

    # Test three different numbers of trees
    'n_estimators': [100, 200],

    # Test three different maximum tree depths
    'max_depth': [3, 5, 7],

    # Test two different minimum sample requirements for splitting
    'min_samples_split': [2, 5],

    # Test two different minimum leaf sizes
    'min_samples_leaf': [1, 2],

    # Use the square-root feature selection strategy
    'max_features': ['sqrt']
}

# Create the Random Forest model that will be tuned
rf_for_grid = RandomForestClassifier(

    # Set a fixed random state so results are reproducible
    random_state=2
)

# Create the GridSearchCV object
grid_search = GridSearchCV(

    # Tell GridSearchCV to tune our Random Forest model
    estimator=rf_for_grid,

    # Provide the smaller parameter grid
    param_grid=param_grid,

    # Use 5-fold cross-validation
    cv=5,

    # Choose the model with the highest accuracy
    scoring='accuracy',

    # Use all available CPU cores
    n_jobs=-1
)

# Train the different Random Forest configurations
grid_search.fit(X_train, Y_train)

# Display the best parameter combination
print("Best Parameters:", grid_search.best_params_)

# Display the best average cross-validation accuracy
print("Best CV Accuracy:", grid_search.best_score_)

Best Parameters: {'max_depth': 3, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 100}
Best CV Accuracy: 0.8635204081632653

In [ ]:
# Get the best Random Forest model found by GridSearchCV
best_rf_model = grid_search.best_estimator_

# Use the tuned Random Forest to make predictions on the training data
Y_train_prediction = best_rf_model.predict(X_train)

# Use the tuned Random Forest to make predictions on the unseen test data
Y_test_prediction = best_rf_model.predict(X_test)

# Calculate the training accuracy of the tuned model
training_accuracy = accuracy_score(Y_train, Y_train_prediction)

# Calculate the test accuracy of the tuned model
test_accuracy = accuracy_score(Y_test, Y_test_prediction)

# Calculate the test precision of the tuned model
test_precision = precision_score(Y_test, Y_test_prediction)

# Calculate the test recall of the tuned model
test_recall = recall_score(Y_test, Y_test_prediction)

# Calculate the test F1 score of the tuned model
test_f1 = f1_score(Y_test, Y_test_prediction)

# Calculate the confusion matrix of the tuned model
test_cm = confusion_matrix(Y_test, Y_test_prediction)

# Print the training accuracy
print("Training Accuracy :", training_accuracy)

# Print the test accuracy
print("Test Accuracy     :", test_accuracy)

# Print the test precision
print("Test Precision    :", test_precision)

# Print the test recall
print("Test Recall       :", test_recall)

# Print the test F1 score
print("Test F1 Score     :", test_f1)

# Print the confusion matrix
print("Confusion Matrix:")
print(test_cm)

Training Accuracy : 0.8925619834710744
Test Accuracy     : 0.7704918032786885
Test Precision    : 0.7878787878787878
Test Recall       : 0.7878787878787878
Test F1 Score     : 0.7878787878787878
Confusion Matrix:
[[21  7]
 [ 7 26]]

# **SVM-SUPPORT VECTOR MACHINE**

In [ ]:
# Import StandardScaler to standardize the numerical features
from sklearn.preprocessing import StandardScaler

# Import Pipeline so scaling and SVM are treated as one complete model
from sklearn.pipeline import Pipeline

# Import SVC, which is the Support Vector Classification algorithm
from sklearn.svm import SVC

# Import cross_val_score to evaluate the model using cross-validation
from sklearn.model_selection import cross_val_score

# Import the evaluation metrics we need
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [ ]:
# Create a pipeline containing both feature scaling and the SVM model
svm_model = Pipeline([

    # Standardize the features so they have comparable scales
    ('scaler', StandardScaler()),

    # Create the SVM classifier using the RBF kernel
    ('svm', SVC(kernel='rbf'))
])

In [ ]:
# Train the complete pipeline using the training data
svm_model.fit(X_train, Y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('svm', SVC())])

In [ ]:
# Use the trained SVM pipeline to predict the training data
Y_train_prediction = svm_model.predict(X_train)

# Use the trained SVM pipeline to predict the unseen test data
Y_test_prediction = svm_model.predict(X_test)

In [ ]:
# Calculate the training accuracy
training_accuracy = accuracy_score(Y_train, Y_train_prediction)

# Calculate the training precision
training_precision = precision_score(Y_train, Y_train_prediction)

# Calculate the training recall
training_recall = recall_score(Y_train, Y_train_prediction)

# Calculate the training F1 score
training_f1 = f1_score(Y_train, Y_train_prediction)

In [ ]:
# Calculate the test accuracy
test_accuracy = accuracy_score(Y_test, Y_test_prediction)

# Calculate the test precision
test_precision = precision_score(Y_test, Y_test_prediction)

# Calculate the test recall
test_recall = recall_score(Y_test, Y_test_prediction)

# Calculate the test F1 score
test_f1 = f1_score(Y_test, Y_test_prediction)

# Calculate the confusion matrix
test_cm = confusion_matrix(Y_test, Y_test_prediction)

In [ ]:
# Print a heading for the SVM results
print("SVM Results")

# Print the training accuracy
print("Training Accuracy :", training_accuracy)

# Print the training precision
print("Training Precision:", training_precision)

# Print the training recall
print("Training Recall   :", training_recall)

# Print the training F1 score
print("Training F1 Score :", training_f1)

# Print the test accuracy
print("Test Accuracy     :", test_accuracy)

# Print the test precision
print("Test Precision    :", test_precision)

# Print the test recall
print("Test Recall       :", test_recall)

# Print the test F1 score
print("Test F1 Score     :", test_f1)

# Print the confusion matrix
print("Confusion Matrix:")

# Display the confusion matrix
print(test_cm)

SVM Results
Training Accuracy : 0.9132231404958677
Training Precision: 0.8936170212765957
Training Recall   : 0.9545454545454546
Training F1 Score : 0.9230769230769231
Test Accuracy     : 0.8032786885245902
Test Precision    : 0.8181818181818182
Test Recall       : 0.8181818181818182
Test F1 Score     : 0.8181818181818182
Confusion Matrix:
[[22  6]
 [ 6 27]]

In [ ]:
# Perform 5-fold cross-validation on the SVM pipeline
svm_cv_scores = cross_val_score(

    # Use the complete scaling plus SVM pipeline
    svm_model,

    # Use the training features
    X_train,

    # Use the training labels
    Y_train,

    # Divide the training data into five folds
    cv=5,

    # Use accuracy as the evaluation metric
    scoring='accuracy'
)

# Print the accuracy obtained from each cross-validation fold
print("SVM Cross-validation scores:", svm_cv_scores)

# Calculate and print the average cross-validation accuracy
print("SVM Mean CV Accuracy:", svm_cv_scores.mean())

SVM Cross-validation scores: [0.79591837 0.91836735 0.79166667 0.89583333 0.79166667]
SVM Mean CV Accuracy: 0.8386904761904763

In [ ]:
param_grid = {
    'svm__C': [0.1, 1, 10, 100],
    'svm__kernel': ['linear', 'rbf'],
    'svm__gamma': ['scale', 'auto']
}

In [ ]:
# Import Pipeline so we can combine preprocessing and the SVM model
from sklearn.pipeline import Pipeline

# Import StandardScaler because SVM is sensitive to feature scales
from sklearn.preprocessing import StandardScaler

# Import the Support Vector Machine classifier
from sklearn.svm import SVC

# Create a pipeline containing scaling followed by SVM
svm_pipeline = Pipeline([

    # Standardize all features before giving them to the SVM
    ('scaler', StandardScaler()),

    # Create the SVM classifier
    ('svm', SVC())
])

In [ ]:
# Import GridSearchCV for finding the best SVM hyperparameters
from sklearn.model_selection import GridSearchCV

# Create the GridSearchCV object
svm_grid = GridSearchCV(

    # Tell GridSearchCV to use our scaling + SVM pipeline
    estimator=svm_pipeline,

    # Give GridSearchCV the SVM parameter combinations to test
    param_grid=param_grid,

    # Use 5-fold cross-validation
    cv=5,

    # Select the model with the highest average accuracy
    scoring='accuracy',

    # Use all available CPU cores to speed up the search
    n_jobs=-1
)

In [ ]:
# Train every SVM configuration using 5-fold cross-validation
svm_grid.fit(X_train, Y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('svm', SVC())]),
             n_jobs=-1,
             param_grid={'svm__C': [0.1, 1, 10, 100],
                         'svm__gamma': ['scale', 'auto'],
                         'svm__kernel': ['linear', 'rbf']},
             scoring='accuracy')

In [ ]:
# Print the hyperparameters that produced the best cross-validation accuracy
print("Best Parameters:", svm_grid.best_params_)

# Print the highest average cross-validation accuracy
print("Best CV Accuracy:", svm_grid.best_score_)

Best Parameters: {'svm__C': 1, 'svm__gamma': 'scale', 'svm__kernel': 'rbf'}
Best CV Accuracy: 0.8386904761904763

In [ ]:
# Get the best SVM pipeline found by GridSearchCV
best_svm_model = svm_grid.best_estimator_

# Print the best SVM pipeline so we can see its preprocessing and model
print(best_svm_model)

Pipeline(steps=[('scaler', StandardScaler()), ('svm', SVC(C=1))])

In [64]:
# Use the best SVM model to predict the unseen test dataset
svm_test_prediction = best_svm_model.predict(X_test)

In [65]:
# Import the evaluation metrics needed to evaluate our SVM
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Calculate the percentage of test predictions that are correct
svm_test_accuracy = accuracy_score(Y_test, svm_test_prediction)

# Calculate how many patients predicted as positive were actually positive
svm_test_precision = precision_score(Y_test, svm_test_prediction)

# Calculate how many actual positive patients were correctly identified
svm_test_recall = recall_score(Y_test, svm_test_prediction)

# Calculate the balance between precision and recall
svm_test_f1 = f1_score(Y_test, svm_test_prediction)

# Calculate the confusion matrix
svm_confusion = confusion_matrix(Y_test, svm_test_prediction)

In [66]:
# Print a heading for the SVM results
print("SVM Results")

# Print the SVM test accuracy
print("Test Accuracy :", svm_test_accuracy)

# Print the SVM test precision
print("Test Precision:", svm_test_precision)

# Print the SVM test recall
print("Test Recall   :", svm_test_recall)

# Print the SVM test F1 score
print("Test F1 Score :", svm_test_f1)

# Print a heading for the confusion matrix
print("Confusion Matrix:")

# Display the confusion matrix
print(svm_confusion)

SVM Results
Test Accuracy : 0.8032786885245902
Test Precision: 0.8181818181818182
Test Recall   : 0.8181818181818182
Test F1 Score : 0.8181818181818182
Confusion Matrix:
[[22  6]
 [ 6 27]]

In [67]:
# Print the best SVM parameters found during cross-validation
print("Best Parameters:", svm_grid.best_params_)

# Print the best average cross-validation accuracy
print("Best CV Accuracy:", svm_grid.best_score_)

Best Parameters: {'svm__C': 1, 'svm__gamma': 'scale', 'svm__kernel': 'rbf'}
Best CV Accuracy: 0.8386904761904763

# **LOGISTIC REGRESSION**

In [69]:
# Import Pipeline so we can combine feature scaling and Logistic Regression
from sklearn.pipeline import Pipeline

# Import StandardScaler to standardize the input features
from sklearn.preprocessing import StandardScaler

# Import Logistic Regression as our next classification model
from sklearn.linear_model import LogisticRegression

# Create a pipeline that first scales the data and then trains Logistic Regression
logistic_pipeline = Pipeline([

    # Standardize the features before giving them to Logistic Regression
    ('scaler', StandardScaler()),

    # Create the Logistic Regression classifier
    ('logistic', LogisticRegression(max_iter=1000))
])

In [70]:
# Create a parameter grid for tuning Logistic Regression
logistic_param_grid = {

    # Test different strengths of regularization
    'logistic__C': [0.01, 0.1, 1, 10, 100],

    # Test both L1 and L2 regularization
    'logistic__penalty': ['l1', 'l2'],

    # Use the solver that supports both L1 and L2 regularization
    'logistic__solver': ['liblinear']
}

In [71]:
# Import GridSearchCV for finding the best Logistic Regression parameters
from sklearn.model_selection import GridSearchCV

# Create the GridSearchCV object for Logistic Regression
logistic_grid = GridSearchCV(

    # Use the scaling and Logistic Regression pipeline
    estimator=logistic_pipeline,

    # Give GridSearchCV the Logistic Regression parameter combinations
    param_grid=logistic_param_grid,

    # Use 5-fold cross-validation
    cv=5,

    # Select the model with the highest average accuracy
    scoring='accuracy',

    # Use all available CPU cores
    n_jobs=-1
)

In [72]:
# Train all Logistic Regression configurations using 5-fold cross-validation
logistic_grid.fit(X_train, Y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('logistic',
                                        LogisticRegression(max_iter=1000))]),
             n_jobs=-1,
             param_grid={'logistic__C': [0.01, 0.1, 1, 10, 100],
                         'logistic__penalty': ['l1', 'l2'],
                         'logistic__solver': ['liblinear']},
             scoring='accuracy')

In [73]:
# Print the best Logistic Regression parameters
print("Best Parameters:", logistic_grid.best_params_)

# Print the best average cross-validation accuracy
print("Best CV Accuracy:", logistic_grid.best_score_)

Best Parameters: {'logistic__C': 0.01, 'logistic__penalty': 'l2', 'logistic__solver': 'liblinear'}
Best CV Accuracy: 0.8344387755102041

In [74]:
# Get the best Logistic Regression pipeline found by GridSearchCV
best_logistic_model = logistic_grid.best_estimator_

# Use the best Logistic Regression model to predict the test data
logistic_test_prediction = best_logistic_model.predict(X_test)

# Calculate the test accuracy
logistic_test_accuracy = accuracy_score(Y_test, logistic_test_prediction)

# Calculate the test precision
logistic_test_precision = precision_score(Y_test, logistic_test_prediction)

# Calculate the test recall
logistic_test_recall = recall_score(Y_test, logistic_test_prediction)

# Calculate the test F1 score
logistic_test_f1 = f1_score(Y_test, logistic_test_prediction)

# Calculate the confusion matrix
logistic_cm = confusion_matrix(Y_test, logistic_test_prediction)

# Print the test accuracy
print("Test Accuracy :", logistic_test_accuracy)

# Print the test precision
print("Test Precision:", logistic_test_precision)

# Print the test recall
print("Test Recall   :", logistic_test_recall)

# Print the test F1 score
print("Test F1 Score :", logistic_test_f1)

# Print the confusion matrix
print("Confusion Matrix:")

# Display the confusion matrix
print(logistic_cm)

Test Accuracy : 0.8032786885245902
Test Precision: 0.8181818181818182
Test Recall   : 0.8181818181818182
Test F1 Score : 0.8181818181818182
Confusion Matrix:
[[22  6]
 [ 6 27]]

In [77]:
# Print the best Logistic Regression hyperparameters found during cross-validation
print("Best Parameters:", logistic_grid.best_params_)

# Print the best average cross-validation accuracy
print("Best CV Accuracy:", logistic_grid.best_score_)

Best Parameters: {'logistic__C': 0.01, 'logistic__penalty': 'l2', 'logistic__solver': 'liblinear'}
Best CV Accuracy: 0.8344387755102041

In [78]:
# Import XGBoost so we can use the XGBClassifier model
from xgboost import XGBClassifier

# Print a message confirming that XGBoost was imported successfully
print("XGBoost is ready!")

XGBoost is ready!

In [79]:
# Import the XGBoost classification model
from xgboost import XGBClassifier

# Create an XGBoost classifier with conservative settings for our small dataset
xgb_model = XGBClassifier(

    # Use 100 boosted trees
    n_estimators=100,

    # Set a relatively small learning rate to reduce overfitting
    learning_rate=0.05,

    # Limit the depth of each tree
    max_depth=3,

    # Require a minimum loss reduction before making a split
    gamma=0,

    # Use row subsampling to add randomness and reduce overfitting
    subsample=0.8,

    # Use feature subsampling to reduce overfitting
    colsample_bytree=0.8,

    # Set a fixed random state so results are reproducible
    random_state=2,

    # Suppress the XGBoost label encoder warning
    eval_metric='logloss'
)

In [80]:
# Train the XGBoost model using the training features and training labels
xgb_model.fit(X_train, Y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=0,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [81]:
# Use XGBoost to predict the unseen test data
xgb_test_prediction = xgb_model.predict(X_test)

# Calculate the XGBoost test accuracy
xgb_test_accuracy = accuracy_score(Y_test, xgb_test_prediction)

# Calculate the XGBoost test precision
xgb_test_precision = precision_score(Y_test, xgb_test_prediction)

# Calculate the XGBoost test recall
xgb_test_recall = recall_score(Y_test, xgb_test_prediction)

# Calculate the XGBoost test F1 score
xgb_test_f1 = f1_score(Y_test, xgb_test_prediction)

# Calculate the XGBoost confusion matrix
xgb_cm = confusion_matrix(Y_test, xgb_test_prediction)

# Print the XGBoost test accuracy
print("Test Accuracy :", xgb_test_accuracy)

# Print the XGBoost test precision
print("Test Precision:", xgb_test_precision)

# Print the XGBoost test recall
print("Test Recall   :", xgb_test_recall)

# Print the XGBoost test F1 score
print("Test F1 Score :", xgb_test_f1)

# Print a heading for the confusion matrix
print("Confusion Matrix:")

# Display the XGBoost confusion matrix
print(xgb_cm)

Test Accuracy : 0.7704918032786885
Test Precision: 0.7878787878787878
Test Recall   : 0.7878787878787878
Test F1 Score : 0.7878787878787878
Confusion Matrix:
[[21  7]
 [ 7 26]]

In [82]:
# Import cross_val_score to evaluate XGBoost using 5-fold cross-validation
from sklearn.model_selection import cross_val_score

# Perform 5-fold cross-validation using XGBoost
xgb_cv_scores = cross_val_score(

    # Use the XGBoost model
    xgb_model,

    # Use the training features
    X_train,

    # Use the training labels
    Y_train,

    # Use five folds
    cv=5,

    # Measure accuracy
    scoring='accuracy'
)

# Print the accuracy obtained from each fold
print("XGBoost CV Scores:", xgb_cv_scores)

# Calculate and print the average cross-validation accuracy
print("XGBoost Mean CV Accuracy:", xgb_cv_scores.mean())

XGBoost CV Scores: [0.81632653 0.91836735 0.75       0.9375     0.75      ]
XGBoost Mean CV Accuracy: 0.8344387755102041

In [83]:
# Get the best Random Forest model found by GridSearchCV
best_rf_model = grid_search.best_estimator_

# Use the tuned Random Forest to predict the unseen test data
rf_test_prediction = best_rf_model.predict(X_test)

# Calculate the tuned Random Forest test accuracy
rf_test_accuracy = accuracy_score(Y_test, rf_test_prediction)

# Calculate the tuned Random Forest test precision
rf_test_precision = precision_score(Y_test, rf_test_prediction)

# Calculate the tuned Random Forest test recall
rf_test_recall = recall_score(Y_test, rf_test_prediction)

# Calculate the tuned Random Forest test F1 score
rf_test_f1 = f1_score(Y_test, rf_test_prediction)

# Calculate the tuned Random Forest confusion matrix
rf_cm = confusion_matrix(Y_test, rf_test_prediction)

# Print the tuned Random Forest test accuracy
print("Test Accuracy :", rf_test_accuracy)

# Print the tuned Random Forest test precision
print("Test Precision:", rf_test_precision)

# Print the tuned Random Forest test recall
print("Test Recall   :", rf_test_recall)

# Print the tuned Random Forest test F1 score
print("Test F1 Score :", rf_test_f1)

# Print a heading for the confusion matrix
print("Confusion Matrix:")

# Display the tuned Random Forest confusion matrix
print(rf_cm)

Test Accuracy : 0.7704918032786885
Test Precision: 0.7878787878787878
Test Recall   : 0.7878787878787878
Test F1 Score : 0.7878787878787878
Confusion Matrix:
[[21  7]
 [ 7 26]]

In [84]:
# Import ROC-AUC so we can measure how well the model separates the two classes
from sklearn.metrics import roc_auc_score

# Get the probability that each test patient belongs to the positive class
logistic_probability = best_logistic_model.predict_proba(X_test)[:, 1]

# Calculate the Logistic Regression ROC-AUC score
logistic_auc = roc_auc_score(Y_test, logistic_probability)

# Print the Logistic Regression ROC-AUC
print("Logistic Regression ROC-AUC:", logistic_auc)

Logistic Regression ROC-AUC: 0.9058441558441559

In [85]:
# Get the probability that each test patient belongs to the positive class
xgb_probability = xgb_model.predict_proba(X_test)[:, 1]

# Calculate the XGBoost ROC-AUC score
xgb_auc = roc_auc_score(Y_test, xgb_probability)

# Print the XGBoost ROC-AUC
print("XGBoost ROC-AUC:", xgb_auc)

XGBoost ROC-AUC: 0.8831168831168832

In [86]:
# Get the probability that each test patient belongs to the positive class
rf_probability = best_rf_model.predict_proba(X_test)[:, 1]

# Calculate the Random Forest ROC-AUC score
rf_auc = roc_auc_score(Y_test, rf_probability)

# Print the Random Forest ROC-AUC
print("Random Forest ROC-AUC:", rf_auc)

Random Forest ROC-AUC: 0.8722943722943722

In [89]:
# Get the SVM decision scores for the test patients
svm_scores = best_svm_model.decision_function(X_test)

# Calculate the SVM ROC-AUC using the decision scores
svm_auc = roc_auc_score(Y_test, svm_scores)

# Print the SVM ROC-AUC
print("SVM ROC-AUC:", svm_auc)

SVM ROC-AUC: 0.8961038961038961